export const ProjectConstant = {
  Packages: [
    'bloc',
    'cached_network_image',
    'calendar_date_picker2',
    'cherry_toast',
    'crop_your_image',
    'dartz',
    'data_table_2',
    'dio',
    'easy_localization',
    'equatable',
    'flutter_bloc',
    'flutter_dotenv',
    'flutter_screenutil',
    'flutter_svg',
    'flutter_upgrade_version',
    'freezed_annotation',
    'get_it',
    'go_router',
    'google_fonts',
    'http',
    'iconsax_plus',
    'image_picker',
    'intl',
    'json_annotation',
    'loading_animation_widget',
    'logger',
    'path',
    'path_provider',
    'photo_view',
    'shared_preferences',
    'toastification',
    'url_launcher',
  ],

  DevPackages: [
    'build_runner',
    'json_serializable',
    'flutter_launcher_icons',
    'flutter_lints',
  ],

  PubspecAssets: [
    'assets:',
    '  - assets/img/',
    '  - assets/translations/',
    '  - .env.dev',
    '  - .env.prod',
    '  - .env.staging',
  ],
};
